const translations = {
  fr: {
    tagline: "Art contemporain & lyrique",
    name: "Nom de l'artiste",
    "nav.home": "Accueil",
    "nav.gallery": "Galerie",
    "nav.available": "Œuvres disponibles",
    "nav.exhibitions": "Expositions",
    "nav.news": "Actualités",
    "nav.concerts": "Concerts",
    "nav.press": "Presse",
    "nav.contact": "Contact",
    "hero.subtitle": "Peinture & voix lyrique",
    "hero.title": "Une œuvre et une voix pour guider le regard",
    "hero.desc": "Plongez dans un univers contemporain où chaque toile dialogue avec le chant. Découvrez les expositions, les concerts et les œuvres disponibles sur demande.",
    "hero.cta": "Voir les œuvres disponibles",
    "hero.secondary": "Dernières actualités",
    "hero.work.label": "Œuvre phare",
    "hero.work.info": "Acrylique sur toile, 120 x 80 cm",
    "hero.work.status": "Pièce de collection (déjà exposée)",
    "about.eyebrow": "À propos",
    "about.title": "Artiste visuelle & chanteuse lyrique",
    "about.lead": "Biographie, démarche et collaborations.",
    "about.bio": "Biographie concise de l'artiste. Ajoutez ici la présentation déjà rédigée, incluant la formation, les influences et les collaborations. Mentionnez l'activité de chanteuse lyrique et les performances marquantes.",
    "about.badge1": "Basée à",
    "about.badge2": "Discipline : peinture, techniques mixtes",
    "about.badge3": "Chant lyrique : récitals & collaborations",
    "about.focus.title": "Ce que le site met en avant",
    "about.focus.item1": "Expositions passées et à venir",
    "about.focus.item2": "Œuvres disponibles sur demande",
    "about.focus.item3": "Agenda concerts et ateliers",
    "about.focus.item4": "Dossiers presse et collaborations",
    "gallery.eyebrow": "Galerie principale",
    "gallery.title": "Parcours visuel",
    "gallery.lead": "Sélection d'œuvres présentées (environ 50 pièces). Liens vers Google Photos pour conserver la qualité.",
    "gallery.work": "Peinture",
    "gallery.details": "Acrylique, 100 x 70 cm — 2023",
    "gallery.unavailable": "Collection privée",
    "gallery.available": "Disponible sur demande",
    "gallery.note": "Ratio visuel : environ 2/3 d'œuvres non disponibles et 1/3 d'œuvres disponibles. Ajoutez vos images haute définition via des liens externes (Google Photos).",
    "available.eyebrow": "Œuvres disponibles",
    "available.title": "Sélection à l'acquisition",
    "available.lead": "Prix sur demande. Contactez l'artiste pour réserver ou organiser une visite d'atelier.",
    "available.detail": "Techniques mixtes, 90 x 90 cm — 2024",
    "available.price": "Prix sur demande",
    "exhibitions.eyebrow": "Expositions",
    "exhibitions.title": "Passées & à venir",
    "exhibitions.upcoming": "Exposition à venir",
    "exhibitions.upcoming.detail": "Galerie Bleu Horizon — Date à confirmer",
    "exhibitions.past1": "Lignes de marée",
    "exhibitions.past1.detail": "Centre d'art Marin — 2024",
    "exhibitions.past2": "Éclats",
    "exhibitions.past2.detail": "Galerie Aurora — 2023",
    "news.eyebrow": "Actualités",
    "news.title": "À la une",
    "news.lead": "Annonces rapides : ateliers, événements spéciaux, nouvelles séries.",
    "news.item.date1": "Mai 2024",
    "news.item.title1": "Atelier immersif « Couleurs marines »",
    "news.item.desc1": "Session limitée à 10 personnes. Réservation par formulaire de contact.",
    "news.item.date2": "Avril 2024",
    "news.item.title2": "Article presse : dialogue entre peinture et voix",
    "news.item.desc2": "Publication dans la revue « Contemporain » — dossier presse disponible.",
    "concerts.eyebrow": "Concerts",
    "concerts.title": "Agenda lyrique",
    "concerts.lead": "Ajoutez facilement vos prochaines dates.",
    "concerts.upcoming": "Prochain concert",
    "concerts.item1.title": "Récital « Vibrations »",
    "concerts.item1.detail": "Théâtre de la Mer — 12 juillet 2024",
    "concerts.item2.title": "Voix & toiles",
    "concerts.item2.detail": "Concert immersif — Date à confirmer",
    "press.eyebrow": "Presse & collaborations",
    "press.title": "Dossiers et partenaires",
    "press.lead": "Ressources pour les galeries, journalistes et partenaires.",
    "press.presskit": "Dossier presse",
    "press.presskit.detail": "PDF haute résolution, biographie complète, visuels téléchargeables.",
    "press.presskit.cta": "Demander l'accès",
    "press.collab": "Collaborations",
    "press.collab.detail": "Projets avec galeries, festivals, marques ou orchestres.",
    "press.collab.cta": "Proposer un projet",
    "contact.eyebrow": "Contact",
    "contact.title": "Échanges & acquisitions",
    "contact.lead": "Formulaire pour galeries, acheteurs, presse ou collaborations.",
    "contact.name": "Nom",
    "contact.email": "E-mail",
    "contact.reason": "Sujet",
    "contact.option.gallery": "Galerie / expo",
    "contact.option.collector": "Acquisition",
    "contact.option.press": "Presse",
    "contact.option.concert": "Concert",
    "contact.option.other": "Autre",
    "contact.message": "Message",
    "contact.note": "Les œuvres sont disponibles sur demande. Un dossier complet vous sera envoyé par e-mail.",
    "contact.submit": "Envoyer",
    "footer.name": "Nom de l'artiste",
    "footer.tagline": "Art contemporain & lyrique",
    "footer.agenda": "Agenda"
  },
  en: {
    tagline: "Contemporary art & lyric voice",
    name: "Artist name",
    "nav.home": "Home",
    "nav.gallery": "Gallery",
    "nav.available": "Available works",
    "nav.exhibitions": "Exhibitions",
    "nav.news": "News",
    "nav.concerts": "Concerts",
    "nav.press": "Press",
    "nav.contact": "Contact",
    "hero.subtitle": "Painting & lyrical voice",
    "hero.title": "A canvas and a voice to lead the gaze",
    "hero.desc": "Step into a contemporary universe where each canvas resonates with voice. Discover exhibitions, concerts, and available works on request.",
    "hero.cta": "View available works",
    "hero.secondary": "Latest news",
    "hero.work.label": "Signature piece",
    "hero.work.info": "Acrylic on canvas, 120 x 80 cm",
    "hero.work.status": "Collector's piece (previously exhibited)",
    "about.eyebrow": "About",
    "about.title": "Visual artist & opera singer",
    "about.lead": "Biography, practice, collaborations.",
    "about.bio": "Concise artist biography placeholder. Insert your prepared text covering training, influences, and collaborations. Mention the lyrical singing activity and key performances.",
    "about.badge1": "Based in",
    "about.badge2": "Mediums: painting, mixed media",
    "about.badge3": "Lyric voice: recitals & collaborations",
    "about.focus.title": "What the site highlights",
    "about.focus.item1": "Past and upcoming exhibitions",
    "about.focus.item2": "Available works on request",
    "about.focus.item3": "Concert and workshop schedule",
    "about.focus.item4": "Press kits and collaborations",
    "gallery.eyebrow": "Main gallery",
    "gallery.title": "Visual journey",
    "gallery.lead": "Selection of displayed works (about 50 pieces). Link to Google Photos to preserve quality.",
    "gallery.work": "Painting",
    "gallery.details": "Acrylic, 100 x 70 cm — 2023",
    "gallery.unavailable": "Private collection",
    "gallery.available": "Available on request",
    "gallery.note": "Visual ratio: roughly 2/3 unavailable pieces and 1/3 available ones. Add your high-resolution images via external links (Google Photos).",
    "available.eyebrow": "Available works",
    "available.title": "Pieces for acquisition",
    "available.lead": "Prices on request. Contact the artist to reserve or arrange a studio visit.",
    "available.detail": "Mixed media, 90 x 90 cm — 2024",
    "available.price": "Price on request",
    "exhibitions.eyebrow": "Exhibitions",
    "exhibitions.title": "Past & upcoming",
    "exhibitions.upcoming": "Upcoming exhibition",
    "exhibitions.upcoming.detail": "Blue Horizon Gallery — Date TBC",
    "exhibitions.past1": "Tidal Lines",
    "exhibitions.past1.detail": "Marine Art Center — 2024",
    "exhibitions.past2": "Shards",
    "exhibitions.past2.detail": "Aurora Gallery — 2023",
    "news.eyebrow": "News",
    "news.title": "Headlines",
    "news.lead": "Quick announcements: workshops, special events, new series.",
    "news.item.date1": "May 2024",
    "news.item.title1": "Immersive workshop 'Sea Colors'",
    "news.item.desc1": "Limited to 10 people. Reserve via the contact form.",
    "news.item.date2": "April 2024",
    "news.item.title2": "Press feature: painting meets voice",
    "news.item.desc2": "Published in 'Contemporain' magazine — press kit available.",
    "concerts.eyebrow": "Concerts",
    "concerts.title": "Lyric schedule",
    "concerts.lead": "Easily add your upcoming dates.",
    "concerts.upcoming": "Next concert",
    "concerts.item1.title": "Recital 'Vibrations'",
    "concerts.item1.detail": "Théâtre de la Mer — 12 July 2024",
    "concerts.item2.title": "Voices & canvases",
    "concerts.item2.detail": "Immersive concert — Date TBC",
    "press.eyebrow": "Press & collaborations",
    "press.title": "Kits and partners",
    "press.lead": "Resources for galleries, journalists, and partners.",
    "press.presskit": "Press kit",
    "press.presskit.detail": "High-res PDF, full bio, downloadable visuals.",
    "press.presskit.cta": "Request access",
    "press.collab": "Collaborations",
    "press.collab.detail": "Projects with galleries, festivals, brands, or orchestras.",
    "press.collab.cta": "Propose a project",
    "contact.eyebrow": "Contact",
    "contact.title": "Inquiries & acquisitions",
    "contact.lead": "Form for galleries, collectors, press, or collaborations.",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.reason": "Subject",
    "contact.option.gallery": "Gallery / exhibition",
    "contact.option.collector": "Acquisition",
    "contact.option.press": "Press",
    "contact.option.concert": "Concert",
    "contact.option.other": "Other",
    "contact.message": "Message",
    "contact.note": "Works are available on request. A full dossier will be emailed to you.",
    "contact.submit": "Send",
    "footer.name": "Artist name",
    "footer.tagline": "Contemporary art & lyric voice",
    "footer.agenda": "Schedule"
  }
};

const i18nElements = document.querySelectorAll('[data-i18n]');
const langButtons = document.querySelectorAll('.lang-btn');
const menuToggle = document.querySelector('.menu-toggle');
const navList = document.getElementById('nav-list');

function setLanguage(lang) {
  const dict = translations[lang];
  i18nElements.forEach((el) => {
    const key = el.getAttribute('data-i18n');
    const value = dict[key];
    if (value) {
      el.textContent = value;
    }
  });
  langButtons.forEach((btn) => {
    const isActive = btn.dataset.lang === lang;
    btn.setAttribute('aria-pressed', isActive);
  });
  document.documentElement.lang = lang;
}

langButtons.forEach((btn) => {
  btn.addEventListener('click', () => {
    setLanguage(btn.dataset.lang);
  });
});

menuToggle.addEventListener('click', () => {
  const expanded = menuToggle.getAttribute('aria-expanded') === 'true';
  menuToggle.setAttribute('aria-expanded', !expanded);
  navList.classList.toggle('open');
});

// Default language
setLanguage('fr');
